[project]
name = "luna"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.6",
    "ty>=0.0.78",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"

[tool.ruff.format]
indent-style = "tab"
nested-string-quote-style = "preferred"
quote-style = "double"

[tool.ruff.lint.isort]
case-sensitive = true
known-first-party = ["luna"]
force-sort-within-sections = true
order-by-type = false
